### ISSUE TITLE
Design database

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#3]
We need to create a database storing all the data that the app will collect. We want to make it so we don't store any Twitter data, but only data needed to figure out what the participant interacted with. 

For our analysis, we will need to compute from the database the following variables (quoted from [Survey Design Document](https://docs.google.com/document/d/1IsetKhYmCcmTUIEK8Yx6eMEkKno3Rxx9SS37GTM29Cg/edit)):

> Feed content outcomes (what is seen) - need to validate what can Truman can measure
>
> - Number of tweets seen (see #4)
> - Slant of tweets seen (Bakshy scores or partisan data from Pulse)
> - Quality of tweets seen (Newsguard score)
>
> Engagement outcomes - need to validate what Truman can measure:
> 
> - Proportion of liked tweets (posted to Twitter or Truman only?) / total tweets seen
> - Slant of links liked (Bakshy scores or partisan data from Pulse)
> - Quality of links liked (Newsguard score)
> - Proportion of clicks of links (Truman only) / all tweets seen
> - Slant of links clicked (Bakshy scores or partisan data from Pulse)
> - Quality of links clicked (Newsguard score)
> - Tweets retweeted (posted to Twitter or Truman only?) / all tweets seen
> - Slant of links retweeted (Bakshy scores or partisan data from Pulse)
> - Quality of links retweeted (Newsguard score)

**Comment by RobertAndion** [comment]
I propose a postgresql database to hold all of this data. We can host it on the same AWS server or have a seperate RDS server. (If we plan to use a load balancer and multiple EC2 instances to control load if many will be using this at the same time, an external RDS would be most ideal since we can have multiple instances accessing the tables at the same time as a remote service.)

Im not sure how to add colors so I will list here. as a list starting with 1 = "Proportion of liked tweets"
1. Yes this is doable. We can check if a tweet was liked before being loaded to Truman as well as new tweets. It is also our job to track all tweets. GREEN
2. Not my place to say yes or no.
3. This should be doable since we can track liked tweets and who posted the liked tweet. YELLOW
4. Should be able to do this. YELLOW
5.  Not my place to say yes or no.
6. Yes this should be traceable once we figure out link embedding then create a listening event of sorts or make it a button. (Saumya will a button work and maybe this will make our issues with embedding the link easier?) YELLOW/GREEN
7. Yes this is trackable. Im not 100% sure what you mean by posted by twitter or truman only. I assume this means if it was already retweented by the user in twitter? Once again this can be tracked before hand and we can even change the buttons to reflect if a tweet has already been liked or retweeted. YELLOW/GREEN
8. Not my place to say yes or no.
9. Yes this should be doable. GREEN

**Comment by glciampaglia** [comment]
We discussed the issue, these are the tables of the database:

* User table, storing information about the participant. This is created when we get a new worker from MTurk / Prime Panels. The ID is the worker ID from the platform. Fields:
  1. Primary key: Worker ID
  2. AssignmentID
  3. HitID
  4. exp_condition - treatment / control
* Tweet table. This stores information about any tweet. It is updated with new tweets when a user loads the newsfeed. Fields:
  1. Primary key: Tweet ID (numerical ID from JSON)
  2. Any other relevant information we want to keep from Twitter.
* Tweet_In_Session table. This stores information about a particular session of a user, and the tweets seen by them. Fields:
  1. Foreign Key: Session ID from session table.
  2. Tweet ID (a person can see multiple tweets, a tweet can be seen by multiple people)
  3. is_favorited_before - from the JSON payload: has the user favorited the tweet before loading Truman?
  4. has_retweet_before - from the JSON payload: has the user retweeted the tweet before loading Truman?
  5. tweet_seen - Boolean: did the user see the tweet during the session on Truman?
  6. tweet_retweeted - Boolean: did the user retweet the tweet during the session on Truman?
  7. tweet_favorited - Boolean: did the user favorite the tweet during the session Truman?
  8. rank - Numerical: the order with which the tweet was displayed
* Session table
  1. Primary key: Session ID (autoincrement)
  2. Worker ID (the person who is using Truman)
  3. Twitter handle used by the worker
  4. session_start - Timestamp: when the session started.
  5. session_end - Timestamp: when the session ended (they logout? or logs out due to inactivity?)
  6. session_timeout - Boolean: the user logged out due to inactivity timeout
* Click table
  1. Primary key: Click ID (autoincrement)
  2. Session ID - the session in which the click occurred (which is associated to a unique worker ID)
  2. Tweet ID - the tweet on which the click occurred
  3. URL - the URL clicked
  4. is_card - Boolean: was the click made on the tweet card?
  5. click_timestamp - the timestamp when the click happened

**Comment by glciampaglia** [comment]
Note that currently Truman is based on Mongo, but the above layout works best with actual SQL. So we decided we will use postgresql instead of Mongo. We will not remove Mongo entirely, as it seems to be too complicated, but rather we will keep it there for dependency.

**Comment by glciampaglia** [comment]
We have a script for creating tables and ran a quick on demo on RDS.
