### ISSUE TITLE
Deploy new beta version on AWS

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#32]
We want to update the old instance that we shared with Brendan to show to YouGov people with then new beta, once the frontend and the backend are able to talk together.

This instance does not need to load tracking events into the database; it's just meant for showing the authentication flow and the feed.

**Comment by saumyabhadani95** [comment]
The frontend and backend are able to talk now. However more discussion is needed regarding the minute details of the database. Right now the database design is still very rough and confusing. Following are the problems:
- I am not inserting the user right now. I don't understand what to insert in the user fields (like assignmentId) which will be different for 1-auth and 2-auth.
- I am also not inserting anything in the association table which was discussed in #30 as I am a bit confused about it. 

We would need more issues to refine the database but since in the current version the required tables are being filled correctly (frontend and backend are able to talk) I am closing this issue.
