### ISSUE TITLE
Keep track of tweets seen

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#4]
As part of the data required by the experiment (see #2), we need to keep track of how many tweets the user saw. We discussed briefly the issue and while we do not know yet how do it in practice, we _think_ there should be a way to have access to this information via the browser. 

We need to investigate possible solutions available:
- Browser scroll events via Javascript --> need to investigate this.
- [Aware framework](https://awareframework.com/)? (Uses smartphone sensors)

**Comment by RobertAndion** [comment]
This seems to be the most challenging task we have at hand. We need to find a way to see how big our tweets are but since that's Pugs job we need to find a way to pass the sizes from pug to a javascript or python tracking script... probably js. Then we need an event to keep track of scroll or swipes and to use some kind of .getPostition() function to get the position from the top in pixels. From that we need to know where it is this location is (i.e. top of screen, middle, bottom) Then we need to know the users screen size and calculate based on position, screen size, and location how many tweets have been seen. We probably also need some kind of await to make sure the person is viewing each tweet for enough time to be counted as a "read". A scroll back up also needs to be accounted for. Furthermore this script would be the perfect catalyst to let the main loop know when it is time to load more tweets. This way it can be done in one script more efficiently (*hopefully).

**Comment by RobertAndion** [comment]
We now have a working prototype for this. It is nearing full functionality but will lack the ability to store the tweets seen until we design our database.

**Comment by glciampaglia** [comment]
We discussed the issue and Robert gave a status update. Currently the only part missing is to be able to keep track of the images --- without images it works fine, with images it is not counting the correct size of the image.

**Comment by RobertAndion** [comment]
There has been a major road block with the image sizes and we cannot find a solution after many hours of trying. We are able to get the width of the picture consistently but the height returns 0 pixels. Our solution now involves using a height to width ration in order to find the height (we have the ability to see the actual height in the browser although it is strangely not working in the code) we have tested that the ratio remains constant when the browser size is changed. There is a small variance between the height to width ratio of some of the images, 10-30px however many seem to be a standard size. 

Our proposal:
We now would propose to average the ratio we get across many images, 20+ to get a "golden ratio" then from this we would calculate the general height based on the width and should get an accurate tracking system.

**Comment by glciampaglia** [comment]
After implementing the ratio technique the tracking works better. We are still working to fix a few small inconstitencies.

**Comment by glciampaglia** [comment]
We have figured out the source of the issue. The image is in a container that retains the same width but not the same height. There seem to be some sub-container that causes the issue. We are currently investigating how to do so in Pug.

**Comment by glciampaglia** [comment]
We briefly discussed that we need to make sure that the information we produce to update the counter will also, once we know the list of tweets, allow us to reconstruct not just _the number_ of tweets seen, but also _which_ tweets were seen. This reconstruction can occur after the user survey.

**Comment by RobertAndion** [comment]
We havent updated this code yet however with our new aspect ratio/image containers it will be much easier to make precise tracking data available. This to be done soon.

**Comment by RobertAndion** [comment]
This was going to be completed this week but will now be put on hold until the image rendering is considered to be better optimized/visually pleasing.

**Comment by RobertAndion** [comment]
This has been adjusted to our new aspect ratio and is done.

**Comment by RobertAndion** [comment]
There seems to be an issue in the function where we are only calculating for one image and need to detect when there are two. @saumyabhadani95  I will need your help on this as you figured out this part.

**Comment by RobertAndion** [comment]
There is a new phenomena that has arisen with our new process. We no longer need to calculate image heights based on aspect ration. The client height function now gets the correct client height for the entire "container". It seems that once javascript gives the image a set size our clientHeight function works properly. This is now working and may only need very minor tweaks after the beta phase.

**Comment by RobertAndion** [comment]
While this is a great new development it also presents a new problem :) For article images it works flawlessly. However with embedded images it is calculating the height of the image for us, unfortunately it is using the original height and not the new one with the applied aspect ratio. @saumyabhadani95 and I must both look at this and see. It may be an order of operations issue (unlikely) or it may be a whole new problem to solve. Fortunately with no embedded images the tracking function is very accurate.

**Comment by RobertAndion** [comment]
This is now complete and is more accurate than ever for both the initial sizes and after a resize.
