### ISSUE TITLE
Problems with link title and description

### ISSUE THREAD

**Issue by filmenczer** [glciampaglia/infodiversity-mock-social-media#41]
Here are other issues with link metadata. In one example the title and description are not properly unescaped (they seem to have HTML-encoded characters). In the other example, there is a link instead of the description?
<img width="1282" alt="Screen Shot 2021-04-01 at 4 33 04 PM" src="https://user-images.githubusercontent.com/10651090/113353582-e7559100-930b-11eb-9fb8-cbd3a262295f.png">
<img width="644" alt="Screen Shot 2021-04-01 at 4 31 20 PM" src="https://user-images.githubusercontent.com/10651090/113353583-e7ee2780-930b-11eb-9a6f-83d77f964c8c.png">

**Comment by RobertAndion** [comment]
This is a strange issue that needs attention. Since the start of this I have been using a python library that is supposed to replace those codes with the proper ASCII values, however it has never worked. More research has to be done by us to find some parsing function that will properly handle this. (The incorrect bottom description goes with the response I had to the parsing issue #40 and will be taken care of.)

**Comment by filmenczer** [comment]
Note that the encoded character might not be ASCII, it might be unicode. Also note the difference between URL (%) encoding and HTML entity (&) encoding.

**Comment by saumyabhadani95** [comment]
We are using BeautifulSoup to parse the HTML file. So this issue should be fixed now.

**Comment by glciampaglia** [comment]
This is mostly fixed. We noticed we also need to unescape the tweet body. We can use the unescape function from xml.sax module, see here: https://wiki.python.org/moin/EscapingHtml

**Comment by RobertAndion** [comment]
This is now done.
