### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by filmenczer** [glciampaglia/infodiversity-mock-social-media#42]
Here is an example where the image is improperly resized, distorting the proportions. The original picture has portrait aspect ratio, and on Twitter it is displayed as cropped. 
<img width="564" alt="Screen Shot 2021-04-01 at 4 37 15 PM" src="https://user-images.githubusercontent.com/10651090/113353875-503d0900-930c-11eb-87af-0e7bdd92ca65.png">

**Comment by RobertAndion** [comment]
It may be possible to keep our aspect ratio and just crop the image to our size however this will look very strange on a very long image. Our compression distorts but keeps the full image as of now. If we just crop a 200x800 pixel image for instance is going to be cropped in half and that may not look nearly as nice.. There is no easy fix for this, as for whatever reason pug does not provide us with the native image sizes. We are unable to leave them as is because then it will be impossible to track in #4 Now that we are using javascript for this some experimentation can be done to see if we are able to get the image height.

**Comment by filmenczer** [comment]
Assuming you are using Twitter API v1.1, look at the documentation [here](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/entities#media-size): you can figure out if the image was fitted or cropped to get the image sizes in the media entity metadata. I think this issue may arise if you take an image size that was cropped and treat it as if it was fitted.

[Photo Media URL formatting](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/entities#photo_format) specifies how to construct different URLs for loading different sized photo media.

**Comment by glciampaglia** [comment]
This seems to affect only the tweets with an image "embedded" in it (i.e. in the JSON). For the tweets with links (where we use a card to show the preview the linked article), the image we get through OG meta tags seems to be always good. 

We can use Pug to select the best image URL based on the photo media URL formatting from Twitter. If however the user resizes the window we need to have an event handler that updates the sizes, otherwise the scroll tracking will be wrong.

**Comment by glciampaglia** [comment]
We are now loading images correctly, based on their aspect ratio (image height to width). If it is above a threshold, we display a cropped image, otherwise, we use the original image. 

However the resizing is still an issue; if one resizes, the scrolling tracker will be off. So we still to need to implement the event handler for the resizing.

**Comment by RobertAndion** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event
Documentation on how to make a resize event

**Comment by RobertAndion** [comment]
Saumya and I have both completed this task and are now trying to figure out how to get it to work in conjunction with the tracking issue.

**Comment by RobertAndion** [comment]
This is completely done and dynamic. In our testing we have seemed to have fixed it all and beta testing is necessary for further validation.
