### ISSUE TITLE
Provide YouGov with authentication endpoint

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#71]
We need to provide YouGov with an authentication endpoint that will return the results of `GET account/settings`. This is needed in the screening survey when the survey asks participants to share their Twitter handle. The participant clicks on a button called "fetch handle" that triggers and authentication workflow. The callback simply returns the JSON payload with [the accounts settings](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/manage-account-settings/api-reference/get-account-settings) of the user.

**Comment by saumyabhadani95** [comment]
I have implemented the authentication workflow in a similar fashion that was shared with us. I just wasn't able to implement the popup. So when the users clicks `Fetch handle` on the initial authentication page, the Twitter page is loaded where the users need to fill their username and password (which was initially in the popup). After the user fills the username and password, the system again loads the initial authentication page with the screen name auto-filled. The JSON payload of the [the accounts settings](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/manage-account-settings/api-reference/get-account-settings) is also stored in the database for YouGov. 

Therefore the workflow is very similar and only the popup is missing. The appearance of the page is also very simple since I don't have all the HTML and CSS files. Closing this issue for now. If these reasons are not trivial we can again reopen the issue.
